[package]
name = "tutorial-2"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustengan"
path = "src/lib.rs"

[[bin]]
name = "rustengan"
path = "src/main.rs"


[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1"
anyhow = "1"