[workspace]
resolver = "2"
members = [
    "tutorial-1",
    "tutorial-2",
    "tutorial-3",
    "tutorial-5"
, "tutorial-6"]


[profile.test]
incremental = false

[profile.dev]
incremental = false

[profile.release]
opt-level = 's'
strip = "debuginfo"
