[package]
name = "tutorial-3"
version = "0.1.0"
edition = "2021"

[lib]
name = "blockchain"
path = "src/lib.rs"

[[bin]]
name = "tutorial-3"
path = "src/main.rs"


[dependencies]
hex = "0.4.3"
crypto-hash = "0.3.3"