[package]
name = "rust-tutorial-1"
version = "0.1.0"
edition = "2021"
description = "This is an implementation of small distributed system based on the Rust"

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1.0.132"
anyhow = "1.0.93"
