[package]
name = "tutorial-1"
version = "0.1.0"
edition = "2021"
description = "Online store library"
license = "MIT"

[[bin]]
name = "tutorial-1"
path = "src/main.rs"

[dependencies]
array_tool = "1.0.3"
